The main module
===============

    >>> from trying import main
    >>> assert 'running of doctests' in main.__doc__

Imports for tests
-----------------

    >>> import os
    >>> import getpass

Trying try
----------

Following tests will only work when run under try itself
    because, e.g. it provides a global called test
    >>> try:
    ...     assert test
    ... except NameError:
    ...     raise KeyboardInterrupt

Running tests with try provides an instance called test
    which has some interesting attributes
    e.g. this file is called main.tests
    >>> assert test.path.name == 'main.test'

If that went well we have a hidden variable called test
    which is an object from the __main__ module
    and has some attributes

    >>> assert test.path_to_py.name == 'main.py'

    >>> assert test.here == os.getcwd()

We also have access to some modules I often use
    without a need for explicit import
    Which ignores the heuristic that
        "Explicit is better than implicit"
    >>> assert test.path.name == makepath(sys.argv[0]).name

And we can run bash commands
    >>> assert bash('/bin/ls /bin/ls')
    /bin/ls

    >>> assert test.home == makepath('~')

We know the user who is running the tests
    >>> assert test.user == '%s@%s' % (getpass.getuser(), test.host)

